"""refac

Revision ID: 0a3892b9e1e9
Revises: 2429a870fdea
Create Date: 2026-03-01 21:33:59.107929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a3892b9e1e9'
down_revision: Union[str, Sequence[str], None] = '2429a870fdea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_types', 'image_url')
    op.add_column('ready_products', sa.Column('name', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ready_products', 'name')
    op.add_column('product_types', sa.Column('image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
