"""init

Revision ID: 1a35c397230a
Revises: 
Create Date: 2026-02-28 17:21:47.440362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1a35c397230a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('hex_code', sa.String(length=7), nullable=False),
    sa.Column('palette_image_url', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.Enum('ready_order', 'custom_order', 'constructor_order', name='paymententitytype'), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('pending', 'succeeded', 'cancelled', name='paymentstatus'), nullable=False),
    sa.Column('yookassa_payment_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('base_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('size_chart_url', sa.String(length=500), nullable=True),
    sa.Column('composition', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('role', sa.Enum('client', 'admin', name='userrole'), server_default='client', nullable=False),
    sa.Column('delivery_name', sa.String(length=200), nullable=True),
    sa.Column('delivery_phone', sa.String(length=20), nullable=True),
    sa.Column('delivery_city', sa.String(length=100), nullable=True),
    sa.Column('delivery_address', sa.String(length=500), nullable=True),
    sa.Column('delivery_carrier', sa.Enum('cdek', 'yandex', name='deliverycarrier'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_table('canvas_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_type_id', sa.Integer(), nullable=False),
    sa.Column('color_id', sa.Integer(), nullable=False),
    sa.Column('canvas_image_url', sa.String(length=500), nullable=True),
    sa.Column('width_px', sa.Integer(), nullable=True),
    sa.Column('height_px', sa.Integer(), nullable=True),
    sa.Column('width_cm', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('height_cm', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('embroidery_zones', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['color_id'], ['colors.id'], ),
    sa.ForeignKeyConstraint(['product_type_id'], ['product_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('print_sizes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('print_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['print_id'], ['prints.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_type_colors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_type_id', sa.Integer(), nullable=False),
    sa.Column('color_id', sa.Integer(), nullable=False),
    sa.Column('in_stock', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['color_id'], ['colors.id'], ),
    sa.ForeignKeyConstraint(['product_type_id'], ['product_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_type_sizes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_type_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=10), nullable=False),
    sa.Column('length', sa.String(length=20), nullable=True),
    sa.Column('width', sa.String(length=20), nullable=True),
    sa.Column('sleeve', sa.String(length=20), nullable=True),
    sa.Column('shoulders', sa.String(length=20), nullable=True),
    sa.Column('waist_width', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['product_type_id'], ['product_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ready_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending_payment', 'paid', 'assembling', 'shipped', 'done', 'cancelled', name='readyorderstatus'), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('carrier', sa.Enum('cdek', 'yandex', name='deliverycarrier_order'), nullable=False),
    sa.Column('delivery_name', sa.String(length=200), nullable=False),
    sa.Column('delivery_phone', sa.String(length=20), nullable=False),
    sa.Column('delivery_city', sa.String(length=100), nullable=False),
    sa.Column('delivery_address', sa.String(length=500), nullable=False),
    sa.Column('tracking_number', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ready_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_type_id', sa.Integer(), nullable=False),
    sa.Column('color_id', sa.Integer(), nullable=False),
    sa.Column('size_label', sa.String(length=10), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stock_quantity', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['color_id'], ['colors.id'], ),
    sa.ForeignKeyConstraint(['product_type_id'], ['product_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cart_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ready_product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ready_product_id'], ['ready_products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('constructor_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('canvas_template_id', sa.Integer(), nullable=False),
    sa.Column('placements', sa.JSON(), nullable=True),
    sa.Column('snapshot_url', sa.String(length=500), nullable=True),
    sa.Column('recommended_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('final_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.Enum('new', 'reviewing', 'accepted', 'paid', 'in_work', 'done', 'cancelled', name='constructororderstatus'), nullable=False),
    sa.Column('admin_comment', sa.Text(), nullable=True),
    sa.Column('carrier', sa.String(length=20), nullable=True),
    sa.Column('delivery_name', sa.String(length=200), nullable=True),
    sa.Column('delivery_phone', sa.String(length=20), nullable=True),
    sa.Column('delivery_city', sa.String(length=100), nullable=True),
    sa.Column('delivery_address', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['canvas_template_id'], ['canvas_templates.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('custom_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_type_id', sa.Integer(), nullable=False),
    sa.Column('color_id', sa.Integer(), nullable=False),
    sa.Column('size_label', sa.String(length=10), nullable=False),
    sa.Column('print_id', sa.Integer(), nullable=True),
    sa.Column('print_size_id', sa.Integer(), nullable=True),
    sa.Column('custom_images', sa.JSON(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('recommended_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('final_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.Enum('new', 'reviewing', 'accepted', 'paid', 'in_work', 'done', 'cancelled', name='customorderstatus'), nullable=False),
    sa.Column('admin_comment', sa.Text(), nullable=True),
    sa.Column('carrier', sa.Enum('cdek', 'yandex', name='deliverycarrier_custom'), nullable=False),
    sa.Column('delivery_name', sa.String(length=200), nullable=False),
    sa.Column('delivery_phone', sa.String(length=20), nullable=False),
    sa.Column('delivery_city', sa.String(length=100), nullable=False),
    sa.Column('delivery_address', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['color_id'], ['colors.id'], ),
    sa.ForeignKeyConstraint(['print_id'], ['prints.id'], ),
    sa.ForeignKeyConstraint(['print_size_id'], ['print_sizes.id'], ),
    sa.ForeignKeyConstraint(['product_type_id'], ['product_types.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ready_order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('ready_product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price_fixed', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['ready_orders.id'], ),
    sa.ForeignKeyConstraint(['ready_product_id'], ['ready_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ready_order_items')
    op.drop_table('custom_orders')
    op.drop_table('constructor_orders')
    op.drop_table('cart_items')
    op.drop_table('ready_products')
    op.drop_table('ready_orders')
    op.drop_table('product_type_sizes')
    op.drop_table('product_type_colors')
    op.drop_table('print_sizes')
    op.drop_table('canvas_templates')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('product_types')
    op.drop_table('prints')
    op.drop_table('payments')
    op.drop_table('colors')
    # ### end Alembic commands ###
