"""refacotred paleete color url

Revision ID: 20777cf844d0
Revises: cecd521e3e21
Create Date: 2026-03-01 17:03:46.480159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20777cf844d0'
down_revision: Union[str, Sequence[str], None] = 'cecd521e3e21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('colors', 'palette_image_url')
    op.add_column('product_types', sa.Column('color_palette_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_types', 'color_palette_url')
    op.add_column('colors', sa.Column('palette_image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
