"""deprecated delivery_hone

Revision ID: cecd521e3e21
Revises: 1a35c397230a
Create Date: 2026-03-01 10:19:16.413326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cecd521e3e21'
down_revision: Union[str, Sequence[str], None] = '1a35c397230a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'delivery_phone')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('delivery_phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
