"""add triggers

Revision ID: e77acb2b52d5
Revises: 0a3892b9e1e9
Create Date: 2026-03-02 15:45:08.631347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e77acb2b52d5'
down_revision: Union[str, Sequence[str], None] = '0a3892b9e1e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_orders', sa.Column('tracking_number', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('custom_orders', 'tracking_number')
    # ### end Alembic commands ###
